### ISSUE TITLE
A question on symbolic link

### ISSUE THREAD

**Issue by guojing0** [othree/markdown-syntax-zhtw#11]
Hi Othree,
I think this project is great. Could you tell me how you set README.md a symbolic link?

**Comment by Vdragon** [comment]
@guojing0 
In Unix-like operating system it's trivial, just use the `ln` command to create the link then commit.
In Microsoft Windows it's much complicated since it's filesystem doesn't support Unix symbolic link at all, it's still possible by using the git command but I currently don't know how.

**Comment by guojing0** [comment]
Thank you. I'll try it some time, if I have relevant problems I may ask you again.‎Best,                                                                                                                                     Sent from my BlackBerry.                                                                                                                                                                                                                                         发件人： Ｖ字龍(Vdragon)已发送： 2015年1月2日星期五 2:56收件人： othree/markdown-syntax-zhtw答复： othree/markdown-syntax-zhtw抄送： Jing Guo主题： Re: [markdown-syntax-zhtw] A question on symbolic link (#11)@guojing0 
In Unix-like operating system it's trivial, just use the ln command to create the link then commit.
In Microsoft Windows it's much complicated since it's filesystem doesn't support Unix symbolic link at all, it's still possible by using the git command but I currently don't know how.

—Reply to this email directly or view it on GitHub.
